services:
  web:
    build: .
    container_name: cinevault
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - /home/admin/projects/cinevault/staticfiles:/app/staticfiles
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=cinevault.nexus.local,192.168.1.9
      - STATIC_ROOT=/app/staticfiles
